linter:
  enabled: true
  APPLY_FIXES: 'true'
  APPLY_FIXES_EVENT: 'pull_request'
  APPLY_FIXES_MODE: 'commit'
  languages:
    - python
    - yaml
    - json
    - markdown
    - dockerfile

python:
  enabled: true
  exclude:
    - "venv/**"
    - "build/**"
    - "dist/**"
  rules:
    - name: pycodestyle
      enabled: true
    - name: pylint
      enabled: true
    - name: flake8
      enabled: true
    - name: pydocstyle
      enabled: true
    - name: bandit
      enabled: true
    - name: mypy
      enabled: true
    - name: markdownlint
      enabled: true
    - name: yamllint
      enabled: true
    - name: jsonlint
      enabled: true
    - name: dockerfilelint
      enabled: true
    - name: shellcheck
      enabled: true