[tool.poetry]
name = "EredesScraper"
version = "0.0.4"
description = "Selenium-based web scraper to extract data from e-Redes website and load it into database storage."
authors = ["Ricardo Filipe dos Santos <ricardofilipecdsantos@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
influxdb-client = "^1.38.0"
openpyxl = "^3.1.2"
pandas = "^2.1.1"
pyyaml = "^6.0.1"
selenium = "^4.14.0"
webdriver-manager = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
